version: '3.7'

services:
  api:
    build: auto_measure_api
    ports:
      - "3000:3000"
    networks:
      - app-network

  react:
    build: auto_measure_react
    ports:
      - '80:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
