version: '3.7'

services:
  api:
    build: auto_measure_api
    ports:
      - '3000:3000'
    env_file: ".env"
    restart: always
    networks:
      - auto_measure_network

  nginx:
    stdin_open: true
    build: 
      context: auto_measure_react
    ports: 
      - '80:80'
    restart: always
    networks:
      - auto_measure_network

networks:
  auto_measure_network:
    driver: bridge